// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqnk_BLYuw_bbyWWW2VH7Jg5F5s1-1x8',
    appId: '1:210178433249:web:d2f8ba5d1a3e94e3b057a0',
    messagingSenderId: '210178433249',
    projectId: 'isamm-news-84a04',
    authDomain: 'isamm-news-84a04.firebaseapp.com',
    storageBucket: 'isamm-news-84a04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnY2HA6OqxTIR0iqA-XNE5UPj9tZhPrEs',
    appId: '1:210178433249:android:1ba780f27a54012db057a0',
    messagingSenderId: '210178433249',
    projectId: 'isamm-news-84a04',
    storageBucket: 'isamm-news-84a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCto8AVsT2k_waLzwZOHh1F3Fg-fZUIq4U',
    appId: '1:210178433249:ios:cd747339f1da9513b057a0',
    messagingSenderId: '210178433249',
    projectId: 'isamm-news-84a04',
    storageBucket: 'isamm-news-84a04.firebasestorage.app',
    androidClientId: '210178433249-0l4pb4tcg8odk2htjf81a799jpiotg60.apps.googleusercontent.com',
    iosClientId: '210178433249-0mib2j8bhcf448iavhqekvdb4p1u8v4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.isammNews',
  );
}
